
language: perl

perl:
  - "5.16"
  - "5.22"

env:
  global:
    - secure: dKPOE1g9wVNXX84n3FHohLOAmyAARGdUdj7bkplEL45+ZBLBJYZrvohP479Wx0YRfp0jC/5lXU0mG5SDlDomFHg2gOIBkDw4mDnaoVdwiyj2H953w7o+/azy6oq3cWsbcGEe9P/IRJrmjrB8p8G+nm4Na/YAaR1MGHmhyU7VqFE=

script:
  - perl Build.PL && ./Build test

after_success:
  - ./Build dist
  - export DIST_FILE=$(ls WTSI-DNAP-Utilities-*.tar.gz)
  - export SHA256_FILE=$DIST_FILE.sha256
  - shasum -a 256 $DIST_FILE > $SHA256_FILE

deploy:
  provider: releases
  api-key: $GH_OAUTH
  file:
    - $DIST_FILE
    - $SHA256_FILE
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
